package m17bfichaaval1;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * @author Rafael Pacheco e Alfredo Bravo
 * @version 0.1, Fev, 9th, 2017
 * 
 * https://github.com/aRafaelPacheco/M17BFichaAval1.git
 * 
 * Ficha de avaliação 1.
 */
public class janela extends javax.swing.JFrame {

    /**
     * Creates new form janela
     */
    public janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ax = new javax.swing.JTextField();
        ay = new javax.swing.JTextField();
        bx = new javax.swing.JTextField();
        by = new javax.swing.JTextField();
        calcula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        y2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calcula.setText("CALCULA");
        calcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        x1.setText("x1");

        x2.setText("x2");

        y1.setText("y1");

        y2.setText("y2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(x1)
                            .addComponent(x2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ax)
                            .addComponent(bx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y1)
                            .addComponent(y2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(by, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcula))
                            .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ax, ay, bx, by});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1)
                    .addComponent(y1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcula)
                    .addComponent(x2)
                    .addComponent(y2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaActionPerformed

        /**
         * criação de dois pontos: p1 & p2. com a técnica de prevenção de erros
         * try{} catch(){}
         */
        try {
            /**
             * Conversão de String para integer x1 é a coordenada X do ponto 1
             * y1 é a coordenada Y do ponto 1
             */
            int x1 = Integer.parseInt(ax.getText());
            int y1 = Integer.parseInt(ay.getText());
            /**
             * Criação do primeiro ponto
             */
            Ponto2D p1 = new Ponto2D(x1, y1);
            /**
             * Conversão de String para integer x2 é a coordenada X do ponto 2
             * y2 é a coordenada Y do ponto 2
             */
            int x2 = Integer.parseInt(bx.getText());
            int y2 = Integer.parseInt(by.getText());
            /**
             * Criação do segundo ponto
             */
            Ponto2D p2 = new Ponto2D(x2, y2);
            /**
             * Chama a função distancia() pelo ponto p2 com o parametro p1
             * (ponto)
             *
             */
            double distancia = p2.distancia(p1);
            textArea.setText(distancia + "");

            /**
             * criação (se ainda não existente) e abertura (se existente) de um
             * ficheiro de texto, chamado "ficheiro.txt" em modo append (true)
             *
             */
            FileWriter f = new FileWriter("ficheiro.txt", true);
            String texto = "Coordenadas:\nPonto 1: " + x1 + " : " + y1 + "\nPonto 2: " + x2 + " : " + y2 + "\nDistância: "
                    + "" + distancia + "\n\n";
            /**
             * Escreve no ficheiro de texto a String texto com os dados
             * relativos às coordenadas dos pontos e a distancia entre os
             * pontos.
             */
            f.write(texto);
            /**
             * Fecho do ficheiro
             */
            f.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_calculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ax;
    private javax.swing.JTextField ay;
    private javax.swing.JTextField bx;
    private javax.swing.JTextField by;
    private javax.swing.JButton calcula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    // End of variables declaration//GEN-END:variables
}
